apiVersion: apps/v1
kind: Deployment
metadata:
  name: departments
spec:
  replicas: 3
  selector:
    matchLabels:
      app-name: departments
  template:
    metadata:
      labels:
        app-name: departments
    spec:
      containers:
        - name: departments
          image: landrzejewski/departments-v1
          ports:
            - containerPort: 8000
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: departments-service
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app-name: departments
