apiVersion: v1
kind: Pod
metadata:
  name: updater-po
spec:
  containers:
    - image: landrzejewski/updater:v1
      name: generator
      volumeMounts:
        - mountPath: /var/htdocs
          name: content
    - image: nginx:1.15.9-alpine
      name: web-server
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: content
  volumes:
    - name: content
      hostPath:
        path: /tmp/content
